describe("RM", () => {
  it("tests RM", () => {
    cy.viewport(2560, 1039);
    cy.visit("chrome://newtab/");
    cy.visit("https://azrb38mabr3xed1.itesoft.local/um/mgr/#/");
    cy.get("#login-tenant").click();
    cy.get("#login-tenant").type("ACME");
    cy.get("#login-user-name").click();
    cy.get("#login-user-name").type("admin");
    cy.get("#login-password").click();
    cy.get("#login-password").type("admin");
    cy.get("form > div > div:nth-of-type(2) span").click();
    cy.get("#navbar-link-organization span.flex-link-text").click();
    cy.get("div:nth-of-type(5) mat-icon").click();
    cy.get("div:nth-of-type(6) mat-icon").click();
    cy.get("#organization-tree-unit-ACME-BAP-label").click();
    cy.get("#organization-tree-unit-rm_flux_bap-label").click();
    cy.get("#organization-button-create mat-icon").click();
    cy.get("#organization-menu-action-create-6 > span").click();
    cy.get("div.ng-star-inserted mat-form-field.um-field div.mat-form-field-infix").click();
    cy.get("#unit-label-0-value").type("S");
    cy.get("#unit-label-0-value").type("Second flow");
    cy.get("#unit-button-validate").click();
    cy.get("#mat-tab-label-0-1").click();
    cy.get("#unit-users-toolbar-button-manage-appointments mat-icon").click();
    cy.get("#user-appointments-input-user-filter").click();
    cy.get("#user-appointments-input-user-filter").type("fgf");
    cy.get("div.cdk-overlay-connected-position-bounding-box span").click();
    cy.get("#user-appointments-input-profile-filter").click();
    cy.get("#user-appointments-input-profile-filter").type("ass");
    cy.get("#mat-option-13 > span").click();
    cy.get("span.mat-slide-toggle-bar").click();
    cy.get("#mat-dialog-title-0 mat-icon").click();
    cy.get("#organization-tree-unit-ACME-BAP").click();
    cy.get("#mat-tab-label-0-1").click();
    cy.get("div:nth-of-type(8) div.unit-label").click();
    cy.get("#mat-tab-label-0-1").click();
    cy.get("#unit-users-toolbar-button-manage-appointments").click();
    cy.get("#user-appointments-input-user-filter").click();
    cy.get("#user-appointments-input-user-filter").type("benoit");
    cy.get("#mat-option-17 > span").click();
    cy.get("#user-appointments-input-profile-filter").click();
    cy.get("#user-appointments-input-profile-filter").type("ass");
    cy.get("#mat-option-20 > span").click();
    cy.get("span.mat-slide-toggle-thumb").click();
    cy.get("#mat-dialog-title-1 mat-icon").click();
    cy.visit("chrome://newtab/");
    cy.visit("https://azrb38mabr3xed1.itesoft.local/portal/?token-id=42f6ef1e-58ff-4059-824b-5622a120f143");
    cy.get("#username").click();
    cy.get("#username").type("benoit");
    cy.get("#password").type("a");
    cy.type("{enter}");
    cy.get("div:nth-of-type(7) img").click();
    cy.get("mat-sidenav-content span > span").click();
    cy.get("#mat-option-1").click();
    cy.get("div.actions-container > app-btn-action:nth-of-type(1) span").click();
    cy.get("td.cdk-column-label input").click();
    cy.get("td.cdk-column-label input").type("label");
    cy.get("td.cdk-column-companyCode input").type("company");
    cy.get("td.cdk-column-siteCode input").type("site");
    cy.get("td.cdk-column-usersLevel1 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(3) > li").click();
    cy.get("p-multiselectitem:nth-of-type(4) > li").click();
    cy.get("div.ng-tns-c46-23 button > span").click();
    cy.get("td.cdk-column-usersLevel2 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(4) > li").click();
    cy.get("div.ng-tns-c46-24 button > span").click();
    cy.get("button.icon-success svg").click();
    cy.get("button.icon-primary svg").click();
    cy.get("td.cdk-column-usersLevel2 span.p-multiselect-token-icon").click();
    cy.get("td.cdk-column-netAmount2 input").click();
    cy.get("td.cdk-column-netAmount2 input").type("1457");
    cy.get("button.icon-success svg").click();
    cy.get("td.cdk-column-usersLevel2 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(2) > li > span").click();
    cy.get("p-multiselectitem:nth-of-type(1) > li").click();
    cy.get("div.p-multiselect-header > button").click();
    cy.get("button.icon-success").click();
    cy.get("button.icon-primary").click();
    cy.get("td.cdk-column-companyCode input").click();
    cy.get("td.cdk-column-companyCode input").type("");
    cy.get("td.cdk-column-siteCode input").click();
    cy.get("button.icon-success svg").click();
    cy.get("button.icon-primary svg").click();
    cy.get("td.cdk-column-siteCode input").click();
    cy.get("td.cdk-column-siteCode input").type("");
    cy.get("button.icon-success svg").click();
    cy.get("td.cdk-column-siteCode input").click();
    cy.get("td.cdk-column-siteCode input").type("site");
    cy.get("td.cdk-column-companyCode input").click();
    cy.get("td.cdk-column-companyCode input").type("company");
    cy.get("td.cdk-column-label input").click();
    cy.get("td.cdk-column-label input").type("");
    cy.get("button.icon-success path").click();
    cy.get("button.icon-primary svg").click();
    cy.get("td.cdk-column-label input").click();
    cy.get("td.cdk-column-label input").type("label");
    cy.get("button.icon-success svg").click();
    cy.get("div.actions-container > div:nth-of-type(1) span").click();
    cy.get("div.actions-container input").type("C:\\fakepath\\approvalroutes (22).csv");
    cy.get("div.cdk-overlay-container button:nth-of-type(1)").click();
    cy.get("div.actions-container > div:nth-of-type(1) span").click();
    cy.get("div.actions-container input").type("C:\\fakepath\\approvalroutes (21).csv");
    cy.get("button.btn-primary").click();
    cy.get("div.cdk-overlay-container button").click();
    cy.get("div.actions-container div.mat-mdc-form-field-infix").click();
    cy.get("#mat-option-0 > span").click();
    cy.get("tr:nth-of-type(1) button.icon-danger svg").click();
    cy.get("button.btn-primary").click();
    cy.get("tr:nth-of-type(2) button.icon-primary svg").click();
    cy.get("button.icon-success svg").click();
    cy.get("tr:nth-of-type(2) button.icon-primary svg").click();
    cy.get("tr:nth-of-type(2) > td.cdk-column-netAmount4 input").click();
    cy.get("tr:nth-of-type(2) > td.cdk-column-netAmount4 input").type("2699");
    cy.get("button.icon-success path").click();
    cy.get("tr:nth-of-type(2) button.icon-primary svg").click();
    cy.get("tr:nth-of-type(2) > td.cdk-column-usersLevel4 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(1) > li > span").click();
    cy.get("p-multiselectitem:nth-of-type(2) > li").click();
    cy.get("div.p-multiselect-header > button").click();
    cy.get("td.cdk-column-usersLevel3 span.p-multiselect-token-icon").click();
    cy.get("button.icon-success path").click();
    cy.get("tr:nth-of-type(2) > td.cdk-column-usersLevel3 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(3) > li > span").click();
    cy.get("p-multiselectitem:nth-of-type(4) > li").click();
    cy.get("p-multiselectitem:nth-of-type(1) > li > span").click();
    cy.get("tr:nth-of-type(2) > td.cdk-column-usersLevel2 span.p-multiselect-token-label").click();
    cy.get("p-multiselectitem:nth-of-type(3) > li").click();
    cy.get("div.p-multiselect-header").click();
    cy.get("div.p-multiselect-header > button").click();
    cy.get("button.icon-success svg").click();
    cy.get("tr:nth-of-type(2) button.icon-primary svg").click();
    cy.get("p-multiselectitem:nth-of-type(3) > li").click();
    cy.get("p-multiselectitem:nth-of-type(11) > li").click();
    cy.get("p-multiselectitem:nth-of-type(12) > li").click();
    cy.get("div.ng-tns-c46-190 button > span").click();
    cy.get("button.icon-success svg").click();
    cy.get("section > div:nth-of-type(2) span > span").click();
    cy.get("#mat-option-3 > span").click();
    cy.get("div:nth-of-type(8) span").click();
    cy.get("#mat-select-value-5").click();
    cy.get("#mat-option-4 > span").click();
    cy.get("div:nth-of-type(5) span").click();
    cy.get("#mat-select-value-5").click();
    cy.get("#mat-option-2").click();
    cy.get("th.cdk-column-companyCode > input").click();
    cy.get("th.cdk-column-companyCode > input").type("acme_a*");
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(1) > button").click();
    cy.get("th.cdk-column-siteCode > input").click();
    cy.get("th.cdk-column-label > input").click();
    cy.get("th.cdk-column-label > input").type("p*");
    cy.get("th.cdk-column-usersLevel2 div.p-multiselect-label-container").click();
    cy.get("div.ng-tns-c46-10 input").type("st");
    cy.get("li > span").click();
    cy.get("div.ng-tns-c46-10 button").click();
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(1) > button").click();
    cy.get("th.cdk-column-netAmount3 div:nth-of-type(2) > input").click();
    cy.get("th.cdk-column-netAmount3 div:nth-of-type(2) > input").type("2000");
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(1) > button").click();
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(2) span").click();
    cy.get("button:nth-of-type(3) img").click();
    cy.location("href").should("eq", "https://azrb38mabr3xed1.itesoft.local/token-provider/user-manager-token-provider/auth?onlyTokenId=true&useCookie=true&returnTo=https://azrb38mabr3xed1.itesoft.local/portal/?token-id=");
    cy.get("#username").click();
    cy.get("#username").type("fgf");
    cy.get("#password").type("a");
    cy.type("{enter}");
    cy.get("div:nth-of-type(5) img").click();
    cy.get("div.actions-container > app-btn-action:nth-of-type(1) > button").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-label input").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-label input").type("label2");
    cy.get("tr:nth-of-type(1) > td.cdk-column-companyCode input").type("company2");
    cy.get("tr:nth-of-type(1) > td.cdk-column-siteCode input").type("site2");
    cy.get("tr:nth-of-type(1) > td.cdk-column-usersLevel1 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(2) > li").click();
    cy.get("p-multiselectitem:nth-of-type(1) > li").click();
    cy.get("div.p-multiselect-header > button").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-netAmount2 input").type("0.01");
    cy.get("tr:nth-of-type(1) > td.cdk-column-netAmount2 input").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-usersLevel2 div.p-multiselect-label-container").click();
    cy.get("div.p-multiselect-footer > button").click();
    cy.get("p-multiselectitem:nth-of-type(36) > li").click();
    cy.get("p-multiselectitem:nth-of-type(35) > li").click();
    cy.get("div.p-multiselect-header > button").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-netAmount3 input").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-netAmount3 input").type("89");
    cy.get("tr:nth-of-type(1) > td.cdk-column-usersLevel3 div.p-multiselect-label-container").click();
    cy.get("div.p-multiselect-filter-container > input").type("ar");
    cy.get("li").click();
    cy.get("button.icon-success svg").click();
    cy.get("tr:nth-of-type(1) button.icon-primary path").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-siteCode input").click();
    cy.get("tr:nth-of-type(1) > td.cdk-column-siteCode input").type("sites");
    cy.get("button.icon-success svg").click();
    cy.get("th.cdk-column-usersLevel1 div.p-multiselect-label-container").click();
    cy.get("p-multiselectitem:nth-of-type(1) > li").click();
    cy.get("div.ng-tns-c46-9 button > span").click();
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(1) > button").click();
    cy.get("div:nth-of-type(2) app-btn-action:nth-of-type(2) path").click();
    cy.get("tr:nth-of-type(1) button.icon-danger path").click();
    cy.get("button.btn-primary").click();
    cy.get("button:nth-of-type(3) img").click();
    cy.location("href").should("eq", "https://azrb38mabr3xed1.itesoft.local/token-provider/user-manager-token-provider/auth?onlyTokenId=true&useCookie=true&returnTo=https://azrb38mabr3xed1.itesoft.local/portal/?token-id=");
  });
});
